# Steps for success:
1. We need to get an API key for zillow and decide how large of a scope we can do. I say we start small and then if everything is great and easy then we can go bigger.
2. We need to find out about the tax website and practice scraping that/get an API.
3. Build a function that gains the info about a specific house from zillow.
4. Build a function that gains the tax info about a specific house.
5. Combine them, testing if it works for one house.
6. Loop for a lot of houses.
7. Build a dataset that we can save off as a csv.
8. Run EDA on the CSV.
9. Build a streamlit app that allows for EDA on the dataset.
10. Build a website that links to the streamlit.
11. Write a report.
12. Add the stuff to our personal portfolios

In [1]:
import os
import requests
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()
api_key = os.getenv('API_KEY')

url = "https://developer.nps.gov/api/v1/parks"
params = {
    'api_key': api_key,
    'limit': 496
}
r = requests.get(url, params=params)
data = r.json()

In [2]:
r.status_code

200

In [22]:
import pandas as pd
df = pd.json_normalize(data['data'])
df = df[df['fullName'].str.contains("National Park")]

df

,id,url,fullName,parkCode,description,latitude,longitude,latLong,activities,topics,...,operatingHours,addresses,images,weatherInfo,name,designation,multimedia,relevanceScore,contacts.phoneNumbers,contacts.emailAddresses
1,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"[{'exceptions': [], 'description': 'Acadia Nat...","[{'postalCode': '04609', 'city': 'Bar Harbor',...","[{'credit': 'NPS / Kristi Rugg', 'title': 'Sun...","Located on Mount Desert Island in Maine, Acadi...",Acadia,National Park,"[{'title': 'Cultural Connections in the Park',...",1.0,"[{'phoneNumber': '2072883338', 'description': ...","[{'description': '', 'emailAddress': 'acadia_i..."
24,36240051-018E-4915-B6EA-3F1A7F24FBE4,https://www.nps.gov/arch/index.htm,Arches National Park,arch,"Discover a landscape of contrasting colors, la...",38.72261844,-109.5863666,"lat:38.72261844, long:-109.5863666",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B'...,...,"[{'exceptions': [], 'description': 'Arches Nat...","[{'postalCode': '84532', 'city': 'Moab', 'stat...","[{'credit': 'NPS/Veronica Verdin', 'title': 'A...","Arches is part of the Colorado Plateau, a ""hig...",Arches,National Park,[],1.0,"[{'phoneNumber': '4357192299', 'description': ...","[{'description': '', 'emailAddress': 'archinfo..."
29,B170CCF7-7AB9-48FF-950E-31815FD4DBB2,https://www.nps.gov/badl/index.htm,Badlands National Park,badl,The rugged beauty of the Badlands draws visito...,43.68584846,-102.482942,"lat:43.68584846, long:-102.482942",[{'id': '5F723BAD-7359-48FC-98FA-631592256E35'...,[{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B'...,...,"[{'exceptions': [], 'description': 'The park i...","[{'postalCode': '57750', 'city': 'Interior', '...","[{'credit': 'NPS Photo', 'title': 'Badlands St...",The Badlands weather is variable and unpredict...,Badlands,National Park,[],1.0,"[{'phoneNumber': '6054335361', 'description': ...","[{'description': '', 'emailAddress': 'badl_inf..."
35,C9056F71-7162-4208-8AE9-2D0AEFA594FD,https://www.nps.gov/bibe/index.htm,Big Bend National Park,bibe,There is a place in Far West Texas where night...,29.29817767,-103.2297897,"lat:29.29817767, long:-103.2297897",[{'id': '5F723BAD-7359-48FC-98FA-631592256E35'...,[{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B'...,...,"[{'exceptions': [], 'description': 'Big Bend N...","[{'postalCode': '79834', 'city': 'Big Bend Nat...","[{'credit': 'NPS', 'title': 'Blooming Cenizo',...",Big Bend is in the Chihuahuan Desert. Sunshine...,Big Bend,National Park,[],1.0,"[{'phoneNumber': '432-477-2251', 'description'...","[{'description': '', 'emailAddress': 'bibe_inf..."
42,FBF9F793-5114-4B61-A5BA-6F9ADDFDF459,https://www.nps.gov/bisc/index.htm,Biscayne National Park,bisc,"Within sight of Miami, yet worlds away, Biscay...",25.490587,-80.21023851,"lat:25.490587, long:-80.21023851",[{'id': '071BA73C-1D3C-46D4-A53C-00D5602F7F0E'...,[{'id': '28AEAE85-9DDA-45B6-981B-1CFCDCC61E14'...,...,"[{'exceptions': [], 'description': 'Launch you...","[{'postalCode': '33033', 'city': 'Homestead', ...","[{'credit': 'NPS image by Shaun Wolfe', 'title...","The park is situated in a subtropical climate,...",Biscayne,National Park,[],1.0,"[{'phoneNumber': '786-335-3620', 'description'...",[{'description': 'If you can't find what you a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,72F41D84-A8ED-47FC-935A-2FD28C3C582E,https://www.nps.gov/wotr/index.htm,Wolf Trap National Park for the Performing Arts,wotr,"No matter what your age or taste in shows, you...",38.93854526,-77.265089,"lat:38.93854526, long:-77.265089",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"[{'exceptions': [], 'description': 'Wolf Trap ...","[{'postalCode': '22182-1643', 'city': 'Vienna'...","[{'credit': 'NPS Photo / N. Adams', 'title': '...",The weather at Wolf Trap National Park for the...,Wolf Trap National Park for the Performing Arts,,[],1.0,"[{'phoneNumber': '7032551800', 'description': ...","[{'description': '', 'emailAddress': 'wotr_int..."
465,B7944940-3FE5-4F9B-80AB-2FD78A4CDD48,https://www.nps.gov/wrst/index.htm,Wrangell - St Elias National Park & Preserve,wrst,Wrangell-St. Elias is a vast national park tha...,61.4182147,-142.6028439,"lat:61.4182147, long:-142.6028439",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B'...,...,"[{'exceptions': [], 'description': 'The park a...","[{'postalCode': '99573', 'city': 'Copper Cente...","[{'credit': 'NPS Photo/ Neal Herbert', 'title'...",Varies widely depending on location in park an...,Wrangell - St Elias,National Park & Preserve,[],1.0,"[{'phoneNumber': '9078225234', 'description': ...","[{'description': '', 'emailAddress': 'wrst_inf..."
468,F58C6D24-8D10-4573-9826-65D42B8B83AD,https://www.nps.gov/yell/index.htm,Yellowstone National Park,yell,"On March 1, 1872, Yellowstone became the first...",44.59824417,-110.5471695,"lat:44.59824417, long:-110.5471695",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '69693007-2DF2-4EDE-BB3B-A25EBA72BDF5'...,...,"[{'exceptions': [], 'description': 'Yellowston...","[{'postalCode': '82190', 'city': 'Yellowstone ...","[{'credit': 'NPS/Jim Peaco', 'title': 'Grand P...","Yellowstone's weather can vary quite a bit, ev...",Yellowstone,National Park,[],1.0,"[{'phoneNumber': '307-344-7381', 'description'...",[{'description': 'Contact Yellowstone's park r...
470,4324B2B4-D1A3-497F-8E6B-27171FAE4DB2,https://www.nps.gov/yose/index.htm,Yosemite National Park,yose,"Not just a great valley, but a shrine to human...",37.84883288,-119.5571873,"lat:37.84883288, long:-119.5571873",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '69693007-2DF2-4EDE-BB3B-A25EBA72BDF5'...,...,"[{'exceptions': [], 'description': 'Yosemite N...","[{'postalCode': '95389', 'city': 'Yosemite Nat...","[{'credit': 'NPS / Cindy Jacoby', 'title': 'Yo...","Yosemite National Park covers nearly 1,200 squ...",Yosemite,National Park,[],1.0,"[{'phoneNumber': '209/372-0200', 'description'...","[{'description': '', 'emailAddress': 'yose_web..."
473,41BAB8ED-C95F-447D-9DA1-FCC4E4D808B2,https://www.nps.gov/zion/index.htm,Zion National Park,zion,Follow the paths where people have walked for ...,37.29839254,-113.0265138,"lat:37.29839254, long:-113.0265138",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '69693007-2DF2-4EDE-BB3B-A25EBA72BDF5'...,...,"[{'exceptions': [], 'description': 'Zion Natio...","[{'postalCode': '84767', 'city': 'Springdale',...","[{'credit': 'NPS/Shane Carte', 'title': 'The W...",Zion is known for a wide range of weather cond...,Zion,National Park,[],1.0,"[{'phoneNumber': '435-772-3256', 'description'...",[{'description': 'If you cannot find what you ...

In [5]:
#Possible use site for ALL nation park annual attendance data
#https://www.nps.gov/aboutus/visitation-numbers.htm

In [ ]:

#df[df['parkCode'] == 'seki']

,id,url,fullName,parkCode,description,latitude,longitude,latLong,activities,topics,...,operatingHours,addresses,images,weatherInfo,name,designation,multimedia,relevanceScore,contacts.phoneNumbers,contacts.emailAddresses
400,7E5A693C-2F63-44FD-B791-31FC8B8B6285,https://www.nps.gov/seki/index.htm,Sequoia & Kings Canyon National Parks,seki,"Huge mountains, rugged foothills, deep canyons...",36.71277299,-118.587429,"lat:36.71277299, long:-118.587429",[{'id': '5F723BAD-7359-48FC-98FA-631592256E35'...,[{'id': '28AEAE85-9DDA-45B6-981B-1CFCDCC61E14'...,...,"[{'exceptions': [], 'description': 'The parks ...","[{'postalCode': '93271', 'city': 'Three Rivers...","[{'credit': 'NPS/Rick Cain', 'title': 'Kings C...",Because of the extreme elevation range in the ...,Sequoia & Kings Canyon,National Parks,[],1.0,"[{'phoneNumber': '5595653341', 'description': ...","[{'description': '', 'emailAddress': 'SEKI_inf..."

In [24]:
#find which park code is npnh
# banlist npnh (National Parks of New York Harbor) because it is not a national park, but a collection of sites (NO POPULATION)

# Remove "banned" park codes
df = df[df['parkCode'] != 'npnh']
df = df[df['parkCode'] != 'seki']

In [26]:
#CSVDictionary.clear()
CSVDictionary = {}

#The park codes from df
park_codes = []
for code in df['parkCode']:
    park_codes.append(code.upper())

park_codes

['ACAD',
 'ARCH',
 'BADL',
 'BIBE',
 'BISC',
 'BLCA',
 'BRCA',
 'CANY',
 'CARE',
 'CAVE',
 'CHIS',
 'CONG',
 'CRLA',
 'CUVA',
 'DEVA',
 'DENA',
 'DRTO',
 'EVER',
 'GAAR',
 'JEFF',
 'GLBA',
 'GLAC',
 'GRCA',
 'GRTE',
 'GRBA',
 'GRSA',
 'GRSM',
 'GUMO',
 'HALE',
 'HAVO',
 'HOSP',
 'INDU',
 'ISRO',
 'JOTR',
 'KATM',
 'KEFJ',
 'KOVA',
 'LACL',
 'LAVO',
 'MACA',
 'MEVE',
 'MORA',
 'NPSA',
 'NERI',
 'NOCA',
 'OLYM',
 'PEFO',
 'PINN',
 'ROMO',
 'SAGU',
 'SHEN',
 'THRO',
 'VIIS',
 'VOYA',
 'WHSA',
 'WICA',
 'WOTR',
 'WRST',
 'YELL',
 'YOSE',
 'ZION']

In [27]:
#Proof of concept for scraping CSV from the above page using Selenium for a SINGLE park (Acadia)

# THIS WILL NEED OT BE ALTERED TO RUN FOR EVERY PARK AND WILL TAKE A LONG TIME TO RUN

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import os
import glob
import pandas as pd
import shutil


for park_code in park_codes:
    print(f"Processing {park_code}...")
    # ----------------------------
    # 1. Setup portable download folder
    # ----------------------------
    download_dir = os.path.join(os.getcwd(), "downloads")
    os.makedirs(download_dir, exist_ok=True)

    options = webdriver.ChromeOptions()
    prefs = {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "download.directory_upgrade": True
    }
    options.add_experimental_option("prefs", prefs)

    # IMPORTANT: only create driver ONCE
    driver = webdriver.Chrome(options=options)

    # ----------------------------
    # 2. Open page
    # ----------------------------

    url = f"https://irma.nps.gov/Stats/SSRSReports/Park%20Specific%20Reports/Annual%20Park%20Recreation%20Visitation%20(1904%20-%20Last%20Calendar%20Year)?Park={park_code}"
    driver.get(url)

    time.sleep(5)

    # ----------------------------
    # 3. Find CSV button in iframes
    # ----------------------------
    iframes = driver.find_elements(By.TAG_NAME, "iframe")

    clicked = False

    for i, frame in enumerate(iframes):
        driver.switch_to.frame(frame)

        try:
            csv_link = WebDriverWait(driver, 5).until(
                EC.presence_of_element_located((By.XPATH, "//a[contains(text(),'CSV')]"))
            )

            driver.execute_script("arguments[0].click();", csv_link)

            print(f"Clicked CSV in iframe {i}")
            clicked = True
            break

        except:
            driver.switch_to.default_content()

    driver.switch_to.default_content()

    # ----------------------------
    # 4. Wait for download to finish
    # ----------------------------
    timeout = 25
    start = time.time()

    latest_file = None

    while time.time() - start < timeout:
        files = glob.glob(os.path.join(download_dir, "*.csv"))
        if files:
            latest_file = max(files, key=os.path.getmtime)
            break
        time.sleep(1)

    # ----------------------------
    # 5. Rename the downloaded file to park-specific name
    # ----------------------------
    new_file_path = os.path.join(download_dir, f"{park_code}.csv")
    shutil.move(latest_file, new_file_path)

    driver.quit()

    # ----------------------------
    # 6. Load CSV safely
    # ----------------------------
    df = pd.read_csv(
        new_file_path,
        skiprows=3   # skips Title + blank lines
    )

    #park_code = "ACAD"

    # clean numbers
    df["RecreationVisitors"] = (
        df["RecreationVisitors"].str.replace(",", "").astype(int)
    )

    CSVDictionary[park_code] = df

    # delete file
    file_path = os.path.join(download_dir, f"{park_code}.csv")

    os.remove(file_path)

    #print(df.head())

Processing ACAD...
Clicked CSV in iframe 0
Processing ARCH...
Clicked CSV in iframe 0
Processing BADL...
Clicked CSV in iframe 0
Processing BIBE...
Clicked CSV in iframe 0
Processing BISC...
Clicked CSV in iframe 0
Processing BLCA...
Clicked CSV in iframe 0
Processing BRCA...
Clicked CSV in iframe 0
Processing CANY...
Clicked CSV in iframe 0
Processing CARE...
Clicked CSV in iframe 0
Processing CAVE...
Clicked CSV in iframe 0
Processing CHIS...
Clicked CSV in iframe 0
Processing CONG...
Clicked CSV in iframe 0
Processing CRLA...
Clicked CSV in iframe 0
Processing CUVA...
Clicked CSV in iframe 0
Processing DEVA...
Clicked CSV in iframe 0
Processing DENA...
Clicked CSV in iframe 0
Processing DRTO...
Clicked CSV in iframe 0
Processing EVER...
Clicked CSV in iframe 0
Processing GAAR...
Clicked CSV in iframe 0
Processing JEFF...
Clicked CSV in iframe 0
Processing GLBA...
Clicked CSV in iframe 0
Processing GLAC...
Clicked CSV in iframe 0
Processing GRCA...
Clicked CSV in iframe 0
Processing GRTE...
Clicked CSV in iframe 0
Processing GRBA...
Clicked CSV in iframe 0
Processing GRSA...
Clicked CSV in iframe 0
Processing GRSM...
Clicked CSV in iframe 0
Processing GUMO...
Clicked CSV in iframe 0
Processing HALE...
Clicked CSV in iframe 0
Processing HAVO...
Clicked CSV in iframe 0
Processing HOSP...
Clicked CSV in iframe 0
Processing INDU...
Clicked CSV in iframe 0
Processing ISRO...
Clicked CSV in iframe 0
Processing JOTR...
Clicked CSV in iframe 0
Processing KATM...
Clicked CSV in iframe 0
Processing KEFJ...
Clicked CSV in iframe 0
Processing KOVA...
Clicked CSV in iframe 0
Processing LACL...
Clicked CSV in iframe 0
Processing LAVO...
Clicked CSV in iframe 0
Processing MACA...
Clicked CSV in iframe 0
Processing MEVE...
Clicked CSV in iframe 0
Processing MORA...
Clicked CSV in iframe 0
Processing NPSA...
Clicked CSV in iframe 0
Processing NERI...
Clicked CSV in iframe 0
Processing NOCA...
Clicked CSV in iframe 0
Processing OLYM...
Clicked CSV in iframe 0
Processing PEFO...
Clicked CSV in iframe 0
Processing PINN...
Clicked CSV in iframe 0
Processing ROMO...
Clicked CSV in iframe 0
Processing SAGU...
Clicked CSV in iframe 0
Processing SHEN...
Clicked CSV in iframe 0
Processing THRO...
Clicked CSV in iframe 0
Processing VIIS...
Clicked CSV in iframe 0
Processing VOYA...
Clicked CSV in iframe 0
Processing WHSA...
Clicked CSV in iframe 0
Processing WICA...
Clicked CSV in iframe 0
Processing WOTR...
Clicked CSV in iframe 0
Processing WRST...
Clicked CSV in iframe 0
Processing YELL...
Clicked CSV in iframe 0
Processing YOSE...
Clicked CSV in iframe 0
Processing ZION...
Clicked CSV in iframe 0

In [28]:
CSVDictionary.keys()

dict_keys(['ACAD', 'ARCH', 'BADL', 'BIBE', 'BISC', 'BLCA', 'BRCA', 'CANY', 'CARE', 'CAVE', 'CHIS', 'CONG', 'CRLA', 'CUVA', 'DEVA', 'DENA', 'DRTO', 'EVER', 'GAAR', 'JEFF', 'GLBA', 'GLAC', 'GRCA', 'GRTE', 'GRBA', 'GRSA', 'GRSM', 'GUMO', 'HALE', 'HAVO', 'HOSP', 'INDU', 'ISRO', 'JOTR', 'KATM', 'KEFJ', 'KOVA', 'LACL', 'LAVO', 'MACA', 'MEVE', 'MORA', 'NPSA', 'NERI', 'NOCA', 'OLYM', 'PEFO', 'PINN', 'ROMO', 'SAGU', 'SHEN', 'THRO', 'VIIS', 'VOYA', 'WHSA', 'WICA', 'WOTR', 'WRST', 'YELL', 'YOSE', 'ZION'])